export default [
    {
        code:'cattleInfoManage',
        name:'牛只信息管理'
    },
    {
        code:'breedFrozenSemen',
        name:'冻精信息'
    },
    {
        code:'breedRegister',
        name:'配种登记'
    },
    {
        code:'breedPregnancyCheck',
        name:'妊检登记'
    },
    {
        code:'breedPregnancyResult',
        name:'产犊登记'
    },
    {
        code:'inventoryBuy',
        name:'外购牛只登记'
    },
    {
        code:'inventorySell',
        name:'出售记录'
    },
    {
        code:'inventoryDeath',
        name:'死亡登记'
    },
    {
        code:'quarantineRegister',
        name:'检疫登记'
    },
    {
        code:'immunityRegister',
        name:'免疫登记'
    }
]